### ISSUE TITLE
Feature request : Simple batch payment

### ISSUE THREAD

**Issue by ffallah** [DefinitelyNotAGoat/payman#3]
Hi,
Thanks for your great work ! I understand that what your program already does is much more sophisticated that what I am going to request but if possible, please consider it.
We already have programs that calculate each delegates share and store it in our database for reporting purposes and etc but as you know tezos-client is unable to send batch payments.
So we have to send payments one by one which is inefficient and takes a few hours to complete.
Can you add the option to get the delegates addresses and payment amounts from command line and send it in one batch payment ?
You may ask why not let the payman calculate everything and send the payment, the reason is that we have specific policies which are not the same for all delegates and payman can not calculate the rewards based on our policies.

Regards

**Comment by DefinitelyNotAGoat** [comment]
Hi @ffallah.

This one might be hard to do because the actual contents of the batch payment are formed in the library Go Tezos: https://github.com/DefinitelyNotAGoat/go-tezos

On that note, payman is supposed to be versatile so name your unique policy, and I'll add a way to calculate rewards in that manner!

**Comment by ffallah** [comment]
Thanks for your reply.
I found this script which does exactly what I was asking for :
https://github.com/figment-networks/tezos-batch-payments
But it would be nice to have this feature in a program written in a robust language like Go.
If I understand correctly, you are calculating the rewards first and then passing them to Go Tezos library to perform the batch payment, so why cant you just read the rewards from command line arguments and send them to Go Tezos library ? just skip the calculation and replace it with reading the rewards from command line.

**Comment by DefinitelyNotAGoat** [comment]
They can be, your right. I will get this added! I'll probably have the input be json.

**Comment by DefinitelyNotAGoat** [comment]
@ffallah I added the feature in v1.02 (https://github.com/DefinitelyNotAGoat/payman/releases). You can now override payman's calculations with by using the ` --payments-override` flag. As an example of it's usage, I have a file called payments.json ( can be any name), that follows this format: 

```
[
  {
      "Address": "KT1W5soiJhwuLaG6eYjhjZPCZfikGMJjSzWE",
      "Amount": 562508162
    },
  {
      "Address": "KT1S1aZU5ATcWRARcq3mVtR9Z5M9ajjjwtv5",
      "Amount": 267494981
    }
]
```

I use payman with all the normal flags with the addition of --payments-override=./payments.json. Payman now pays out using the above payments: https://alphanet.tzscan.io/onjzED1pmmrNZS21MyMENKvj6YbcgAuVdYS4uYyjwjtnuGwCNrQ

Let me know if you have any questions!
