### ISSUE TITLE
Feature request: support for minimum payouts

### ISSUE THREAD

**Issue by leopoldjoy** [DefinitelyNotAGoat/payman#7]
Many bakers choose to only payout delegators who have accrued reward that exceeds a predefined minimum payout. Currently this is not possible with Payman (without manually providing the overwritten payouts JSON).

**Comment by DefinitelyNotAGoat** [comment]
Yeah this has been on my back burner too. I'll get this out for v1.0.4.

**Comment by leopoldjoy** [comment]
@DefinitelyNotAGoat Perfect, thank you! Any idea of the _rough_ ETA for `v1.0.4`?

I'll also try to hop into the codebase if I can find any extra time.

**Comment by DefinitelyNotAGoat** [comment]
I'll get it out tonight, it shouldn't take too long!

**Comment by leopoldjoy** [comment]
Fantastic, thank you @DefinitelyNotAGoat! 🚀

**Comment by DefinitelyNotAGoat** [comment]
You should be all set: https://definitelynotagoat.github.io/payman/
```
wget https://github.com/DefinitelyNotAGoat/payman/releases/download/v1.0.4/payman_darwin_amd64
sudo mv payman_linux_amd64 /usr/local/bin/payman
sudo chmod a+x /usr/local/bin/payman
```
